name: Build F-Droid APK

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Manual override version tag (optional)"
        required: false

jobs:
  build:
    name: Build F-Droid Release
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${{ github.event.release.tag_name || github.event.inputs.version || 'latest' }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Update app version
        run: |
          cd mobile
          # Update pubspec.yaml version
          if [[ "$IMAGE_TAG" != "latest" ]]; then
            sed -i "s/^version: .*/version: ${IMAGE_TAG#v}/" pubspec.yaml
          fi

      - name: Build F-Droid APK (unsigned)
        run: |
          cd mobile
          flutter build apk --release
          
      - name: Rename APK for F-Droid
        run: |
          cd mobile
          cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/PinePods-fdroid-${IMAGE_TAG#v}.apk

      - name: Upload F-Droid APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-apk-build
          path: mobile/build/app/outputs/flutter-apk/PinePods-fdroid-*.apk